# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('size', models.IntegerField(choices=[(1, 'Extra Small'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Extra Large')], default=3)),
                ('price', models.FloatField(default=2450)),
                ('type', models.TextField(max_length=40)),
                ('model', models.TextField(max_length=40)),
                ('year', models.IntegerField()),
                ('serialNumber', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='bikes_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='BikeShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('address', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BikeShops_Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Bikes')),
                ('bikeshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
            ],
        ),
        migrations.CreateModel(
            name='BikeShops_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('state', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
                ('address', models.TextField(max_length=50)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Companies_Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Bikes')),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerServiceRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_vin', models.TextField(max_length=100)),
                ('time_requested', models.DateTimeField()),
                ('bikeshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('price', models.TextField()),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customerservicerequests',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Services'),
        ),
        migrations.AddField(
            model_name='customerservicerequests',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cities',
            unique_together=set([('name', 'state')]),
        ),
        migrations.AddField(
            model_name='bikeshops_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Products'),
        ),
        migrations.AddField(
            model_name='bikeshops',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Cities'),
        ),
        migrations.AlterUniqueTogether(
            name='customerservicerequests',
            unique_together=set([('time_requested', 'bike_vin', 'user_id', 'service_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='companies_bikes',
            unique_together=set([('company_code', 'bike_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='companies',
            unique_together=set([('name', 'address', 'city_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bikeshops_products',
            unique_together=set([('bikeshop_id', 'product_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bikeshops_bikes',
            unique_together=set([('bikeshop_id', 'bike_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bikeshops',
            unique_together=set([('city_id', 'address', 'name')]),
        ),
    ]
