# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=40)),
                ('model', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BikeShops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('address', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BikeShops_Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Bikes')),
                ('bikeshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
            ],
        ),
        migrations.CreateModel(
            name='BikeShops_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('bikeshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
            ],
        ),
        migrations.CreateModel(
            name='BikeShopServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('state', models.TextField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=40)),
                ('address', models.TextField(max_length=50)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Companies_Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Bikes')),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Companies_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=40)),
                ('last_name', models.TextField(max_length=40)),
                ('address', models.TextField(max_length=40)),
                ('email', models.TextField(max_length=50)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Cities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer_Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Bikes')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerServiceRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_requested', models.DateTimeField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Bikes')),
                ('bikeshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=40)),
                ('last_name', models.TextField(max_length=40)),
                ('address', models.TextField(max_length=40)),
                ('title', models.TextField(max_length=40)),
                ('salery', models.FloatField()),
                ('bikeshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Cities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('description', models.TextField(max_length=100)),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('estimated_finish', models.DateTimeField()),
                ('description', models.TextField(max_length=100)),
                ('scheduled_start_date', models.DateTimeField()),
                ('bike_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Bikes')),
            ],
        ),
        migrations.CreateModel(
            name='ShopEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.BikeShops')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Employees')),
            ],
        ),
        migrations.AddField(
            model_name='customerservicerequests',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Services'),
        ),
        migrations.AddField(
            model_name='companies_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Products'),
        ),
        migrations.AlterUniqueTogether(
            name='cities',
            unique_together=set([('name', 'state')]),
        ),
        migrations.AddField(
            model_name='bikeshopservices',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Services'),
        ),
        migrations.AddField(
            model_name='bikeshops_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Products'),
        ),
        migrations.AddField(
            model_name='bikeshops',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Cities'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Companies'),
        ),
        migrations.AlterUniqueTogether(
            name='shopemployees',
            unique_together=set([('person_id', 'bike_shop_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='services',
            unique_together=set([('bike_id', 'scheduled_start_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='customerservicerequests',
            unique_together=set([('time_requested', 'bike_id', 'person_id', 'service_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='customer_bikes',
            unique_together=set([('person_id', 'bike_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='companies_products',
            unique_together=set([('company_id', 'product_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='companies_bikes',
            unique_together=set([('company_code', 'bike_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='companies',
            unique_together=set([('name', 'address', 'city_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bikeshopservices',
            unique_together=set([('bikeshop_id', 'service_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bikeshops_products',
            unique_together=set([('bikeshop_id', 'product_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bikeshops_bikes',
            unique_together=set([('bikeshop_id', 'bike_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bikeshops',
            unique_together=set([('city_id', 'address', 'name')]),
        ),
    ]
