# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=40)),
                ('last_name', models.TextField(max_length=40)),
                ('address', models.TextField(max_length=40)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShop.Cities')),
            ],
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='bikes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bikeshops_bikes',
            name='price',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='last_name',
        ),
        migrations.AddField(
            model_name='bikes',
            name='price',
            field=models.FloatField(default=2450),
        ),
        migrations.AddField(
            model_name='bikes',
            name='serialNumber',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikes',
            name='size',
            field=models.IntegerField(choices=[(1, 'Extra Small'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Extra Large')], default=3),
        ),
        migrations.AddField(
            model_name='bikes',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='bikes_pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companies',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='people_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BikeShop.People'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='people_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BikeShop.People'),
            preserve_default=False,
        ),
    ]
