# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShop', '0003_auto_20170424_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
    ]
