# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShop', '0004_bikes_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companies_products',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='companies_products',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='companies_products',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='bikeshops_products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Companies_Products',
        ),
    ]
